# Generated by Django 4.2.1 on 2023-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='tunisia', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='9485200', max_length=12),
            preserve_default=False,
        ),
    ]
