# Generated by Django 4.2.1 on 2023-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0003_rename_qualifcation_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualifications',
            field=models.ManyToManyField(related_name='profiles', to='cvgen.qualification'),
        ),
    ]
