# Generated by Django 4.2.1 on 2023-05-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0004_profile_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cvgen.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cvgen.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cvgen.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvgen.profile'),
        ),
    ]
