# Generated by Django 4.2.1 on 2023-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0005_employmenthistory_remove_profile_education_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistory',
            name='date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='period',
            field=models.DateField(max_length=255),
        ),
    ]
