# Generated by Django 4.2.1 on 2023-05-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0007_remove_task_skill_skill_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cvgen.skill'),
            preserve_default=False,
        ),
    ]
