# Generated by Django 4.2.1 on 2023-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0008_remove_skill_tasks_task_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='tasks',
            field=models.ManyToManyField(to='cvgen.task'),
        ),
    ]
