# Generated by Django 4.2.1 on 2023-05-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0010_remove_skill_tasks_task_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='task',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
