# Generated by Django 4.2.1 on 2023-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0011_skill_task_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistory',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='period',
            field=models.CharField(max_length=255),
        ),
    ]
